name: java-maven-dependency-check-action
on:
  workflow_dispatch:
    inputs:   
      java-version:
        description: 'Version of Java to build with'
        default: '8'
        required: false
jobs:
  dependency-check:
    name: dependency-check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-owasp-
  
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: corretto
        java-version: ${{ inputs.java-version || '8' }}
      
    - name: Dependency check with org.owasp:dependency-check-maven
      shell: bash
      run: mvn org.owasp:dependency-check-maven:8.1.2:aggregate -Dformats=SARIF -Dodc.outputDirectory=${{ github.workspace }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2.1.32
      with: 
        sarif_file: ${{ github.workspace }}/dependency-check-report.sarif

    # - name: Print CVE Summery on GITHUB_STEP_SUMMARY # https://miller.readthedocs.io/en/latest/
    #   shell: bash
    #   run: |
    #     docker run --rm -i jauderho/miller:latest --omd --icsv cut -f CVE,Identifiers,CVSSv2_Severity < target/dependency-check-report.csv >> $GITHUB_STEP_SUMMARY
    #     echo >> $GITHUB_STEP_SUMMARY
    #     echo "Download the Artifact dependency-check-report to see more details" >> $GITHUB_STEP_SUMMARY
        
    # - name: Archive dependency-check-report as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dependency-check-report
    #     path: ${{ github.workspace }}/target/dependency-check-report.csv