name: Java CI with Maven , reusable GHA workflow
on:
  workflow_dispatch:
    inputs:
      java-version:
        description: java version to be used
        required: true
      app-name:
        description: application name
        required: false
  push:
    branches: [ "master" ]
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  build-and-test:
    uses: cnighojkar/myworkflows/.github/workflows/java-maven-build-test.yml@main
    with:
      java-version: ${{ github.event.inputs.java-version }}
      app-name: javulna-1.0-SNAPSHOT
    secrets: inherit